package(default_visibility = ["//visibility:public"])

java_library(
    name = "ballerina-tools-api",
    srcs = glob([
        "src/main/java/**/*.java",
    ]),
    visibility = ["//visibility:public"],
    deps = [],
)

load("@j2cl//build_defs:rules.bzl", "j2cl_library")

j2cl_library(
    name = "ballerina-tools-api-j2cl",
    srcs = glob([
        "src/main/java/**/*.java",
    ], exclude=["src/main/java/**/*Native.java", "src/main/java/**/Env.java", "src/main/java/**/DefaultDiagnostic.java"]) + glob([
        "super-j2cl/**/*.java",
    ]),
    deps = [

    ],
    javacopts = [
        "-source", "21",
        "-target", "21",
    ],
)
