package(default_visibility = ["//visibility:public"])

java_library(
    name = "ballerina-envutils",
    srcs = glob([
        "src/main/java/**/*.java",
    ]),
    visibility = ["//visibility:public"],
    deps = [],
)

load("@j2cl//build_defs:rules.bzl", "j2cl_library")

j2cl_library(
    name = "ballerina-envutils-j2cl",
    srcs = glob([
        "src/main/java/**/*.java",
    ], exclude=["src/main/java/**/*Native*.java", "src/main/java/**/Env.java", "src/main/java/**/Path.java", "src/main/java/**/Console.java", "src/main/java/**/module-info.java"]) + glob([
        "super-j2cl/**/*.java",
    ]),
    deps = [
        "@j2cl//:jsinterop-annotations-j2cl",
    ],
    javacopts = [
        "-source", "21",
        "-target", "21",
    ],
)
